name: Rebuilderz
favicon: null
layout_spectrum: 0.3656915526371449
typography_spectrum: 0.14386388333514333
title: Rebuilderz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f7fbf7'
    - '#c0c0c0'
    - '#6f5b3e'
    - '#898989'
  brandStrength: 0.8532460106071085
  lightness: 0.3122908629011363
  saturation: 0.6468771824147552
  rhythmicContrast: 0.26664918730966747
purpose: []
